	
These Terms of Use ("Terms of Use" or "Agreement") shall serve as an agreement that sets forth the terms and conditions which will govern your use and participation in the transaction management and escrow services provided on and through Escrow Services (the "Services"). By electing to utilize the Services you shall have also indicated your acceptance of these Terms of Use and your intent and agreement to be bound by them. If you are unwilling to agree to these Terms of Use, you shall discontinue further use of the Services. If you agree to these Terms of Use, you will be bound as follows:

1. Definitions. "Account" means (i) an account of a Buyer from which payment for the Transaction and related fees will be obtained, (ii) an account of a Seller to which payment for the Transaction and other payments will be credited, or (iii) an account of a Broker to which payment for the Transaction and other payments will be credited and/or related fees will be obtained. "Agreement" refers to this Agreement, the then current operating rules contained on the Site and the Transaction Escrow Instructions. "Transaction Detail Screens" means those screens on the Site where Users provide all requested information in connection with a Transaction. "Escrow Instructions" or "General Instructions" means the document on the Site that contains the terms agreed upon on the Transaction Detail Screens, as well as the other terms and conditions of the escrow transaction including these Terms of Use. "User" means Buyer(s), Seller(s), and Broker(s) participating in a Transaction. "Site" refers to the website for the Services which can be found at Escrow Services. Capitalized terms not defined herein shall have the same meaning as set forth in the General Escrow Instructions.

2. Description of the Service. The Services are Internet-based transaction management services performed by Escrow Services and escrow services provided by Internet Escrow Services, Inc., a California corporation “IES,” acts as escrow agent in a Transaction, which Services are intended to facilitate the completion of the underlying transaction under the terms of this Agreement, the Site and the applicable Transaction Escrow Instructions.

3. Limits on the Services. The Services are only available for lawful items and items not otherwise excluded by Section 4 below. Limitations on the Services may apply and can be found on the Site or in the General Escrow Instructions or Transaction Escrow Instructions. Only registered Users may use the Services. In order to register, you must supply all information required on the Site. Applicable state or federal laws and regulations may further limit the Services.

4. Prohibited Transactions. Users shall not utilize the Site or the Services in connection with any Transaction that is illegal or involves any illegal items, or is for any illegal purpose; involves any obscene material; involves any munitions or firearm; involves pirated software, DVD or videos or item(s) otherwise infringing copyrighted works; involves illegal drugs or controlled substances; involves real property or any interest in real property, the sale or transfer of liquor licenses, the sale of a business (bulk sale), the transfer of title to a business entity, fund or joint control escrows, mobile homes or manufactured homes or the refinancing of either, reservation deposits of any kind, or promissory notes, mortgages or deeds of trust. In addition, Escrow Services, in its sole discretion, may refuse to complete any Transaction that Escrow Services has reason to believe is unauthorized or made by someone other than you, may violate any law, rule or regulation, or if Escrow Services has reasonable cause not to honor it. Each User agrees to indemnify and hold Escrow Services harmless for losses resulting from any use or attempted use of the Services in violation of this Agreement.

5. Rejection of Payment. Since the use of a bank account, credit card or debit card account, or the making of an electronic funds transfer may be limited by your agreement with your financial institution and/or by applicable law, Escrow Services is not liable to any User if Escrow Services does not complete a Transaction as a result of any such limit, or if a financial institution fails to honor any credit or debit to or from an Account. Escrow Services may post operating rules related to payment on the Site and change such rules from time to time.

6. General Conditions of Use. If you arrive at the Site through entities linked and/or integrated with Escrow Services or otherwise by or through a third party (e.g., an auction, exchange, or Internet-based intermediary that hosts electronic marketplaces and mediates transactions among businesses), then you authorize such third party to transfer relevant data to Escrow Services to facilitate the Transaction. You represent and warrant that all information you provide to Escrow Services or to such third party will be true, accurate and complete. The party entering into this Agreement on behalf of any User represents and warrants that he/she is authorized to do so and to bind the User and is a natural person of at least eighteen (18) years of age. In order to initiate and commence a Transaction, all Users to a Transaction must register at the Site, agree to all terms in the General Escrow Instructions and agree to the Transaction Escrow Instructions.

7. Obligations of Sellers. On the Transaction Detail Screens, each Seller to a Transaction must designate an Account to which payment for the Transaction will be made. Each Seller authorizes IES and its authorized agents to initiate credit entries to such Seller's Account for payment of the purchase price, or applicable balance due, and to debit Seller's Account to discharge Seller's obligations. Each Seller in a Transaction shall deliver the items set forth in Transaction Detail Screens directly to the Buyer (or Buyers), at the address specified by such Buyer as shown on the Escrow Services website and on the terms and conditions set forth in the Transaction Escrow Instructions and General Escrow Instructions. Seller shall use a delivery service that provides a confirmation of delivery and Seller shall provide Escrow Services with a tracking or reference number for the shipment of the goods. Seller gives Escrow Services permission to act as its agent in communicating with the shipping company regarding the notice of the delivery of the goods. In the event Escrow Services does not receive notice of shipment from Seller within ten (10) calendar days of notification from Escrow Services's notice to Seller to ship the items, Seller authorizes Escrow Services to return the escrowed funds (excluding Escrow Services fees) to Buyer. In the event of a return of the items by Buyer, Seller shall notify Escrow Services of the receipt of the returned items. Upon receipt of such notice from Seller, the Seller's five (5) day inspection period shall commence. In the event Seller accepts the returned items within the inspection period or fails to act within the inspection period, Escrow Services shall remit the escrowed funds (excluding Escrow Services fees) to Buyer. If Seller notifies Escrow Services of its non-acceptance of any returned items within the Seller's inspection period, then Escrow Services will retain the escrow funds pending resolution of the dispute or take other action as authorized. Notwithstanding anything to the contrary above, if all Users to a Transaction agree on the Transaction Detail Screens that there is no shipping required, then no party hereto will have any obligation under this Agreement with respect to shipping.

8. Obligations of Buyers. On the Transaction Detail Screens, Buyer must designate a payment mechanism and an Account from which the purchase price and related fees (unless such fees are to be paid by Seller) will be obtained for the deposit into escrow. Depending on the amount of the Transaction and the currency selected for the Transaction, Buyer may remit the necessary funds via various methods, which may include corporate credit card, charge card, debit card or purchasing card, check (cheque), cashier's check, money order, or wire transfer. In the case of wire transfers, Buyer will initiate the wire to an account designated by Escrow Services on or before the date set forth in the Transaction Detail Screens. Regardless of the payment method, Buyer authorizes Escrow Services and Escrow Services authorized agents to initiate credit or debit transactions, as applicable, to obtain the purchase price and fees due for a Transaction and to initiate any debit or credit entries or reversals, as the case may be, as may be necessary to correct any error in a payment or transfer and to discharge Buyer's obligations under Section 22 of this Agreement. Escrow Services will deposit funds received from Buyer into an escrow trust account maintained by Escrow Services (the "Escrow Account"). Unless otherwise requested as specified in the following sentence, escrowed deposits do not earn interest for Buyer or Seller. If you anticipate an extended closing of the Transaction, then you may request and approve an instruction to have Escrow Services place Buyer's funds into an interest bearing account for the benefit of Buyer or Seller. If interest is to accrue to the benefit of the Seller, then both Buyer and Seller must request and approve the establishment of the interest bearing account. If this request is made, then Escrow Services will charge the account of the party to whom the interest accrues an additional nonrefundable service charge of $100.00, which must be paid in advance.

Buyer shall notify Escrow Services of the receipt or non-receipt of the items on the date the merchandise is received or the Buyer Inspection Period is started. Buyer shall notify Escrow Services of the Buyer's acceptance or rejection of the items before the Buyer's Inspection Period expires. Upon receipt of notice from Buyer that the items have been received and accepted, Escrow Services shall transfer the payment amount (less any amount payable to Escrow Services for Escrow Services fees) to Seller's Account. Transfer to a Seller generally will be initiated within the next business day from the day on which notice of acceptance of the items is received from the Buyer. If Buyer has not notified Escrow Services of the non-receipt or rejection of the items during the Buyer's Inspection Period, then Buyer authorizes Escrow Services to remit the escrowed funds (excluding Escrow Services fees) to the Seller. Buyer shall follow the procedures set forth on the Site in the event the items are rejected.

9. Obligations of Brokers. On the Transaction Detail Screens, each Broker to a Transaction must designate an Account to which the Broker Fee payment will be made. Each Broker authorizes IES and its authorized agents to initiate credit entries to such Broker's Account for payment of the Broker's commission, and to debit Broker's account to discharge Broker's obligations. Each Broker in a Transaction shall provide Buyer email, Seller email, and Transaction details including purchase price, merchandise description, inspection period and which party is responsible for the Broker and Escrow fees.

10. Our Responsibilities. Escrow Services is obligated to perform only those duties expressly described in this Agreement and the General Escrow Instructions. Escrow Services shall not be liable for any error in judgment, for any act taken or not taken, or for any mistake of fact or law, except for gross negligence or willful misconduct (subject to the limitations in Section 17 below). Escrow Services may rely upon any notice, demand, request, letter, certificate, agreement or any other document which purports to have been transmitted or signed by or on behalf of a User indicated as the sender or signatory thereof and shall have no duty to make any inquiry or investigation. In the event that Escrow Services is uncertain as to Escrow Services duties or rights under this Agreement, receives any instruction, demand or notice from any User or financial institution which, in Escrow Services's opinion, is in conflict with any of the provisions of this Agreement, or any dispute arises with respect to this Agreement or the Escrowed Funds, Escrow Services may (i) consult with counsel of our choice (including our own attorneys) and any actions taken or not taken based upon advice of counsel shall be deemed consented to by you, or (ii) refrain from taking any action other than to retain the funds in escrow for delivery in accordance with the written agreement of the Users, the final decision or award of an arbitrator pursuant to an arbitration commenced and conducted in accordance with the General Escrow Instructions or a final, non-appealable judgment of a court of competent jurisdiction, or (iii) discharge our duties under this Agreement by depositing all funds by interpleader action with a court of competent jurisdiction in accordance with the procedures outlined in the General Escrow Instructions.

Escrow Services may, at any time, give notice of Escrow Services's intent to resign as Escrow Agent. If, within ten (10) days of such notice, Escrow Services has not received notice from all Users in a Transaction that they have designated a substitute escrow agent (which notice shall identify the substitute escrow agent), Escrow Services may discharge Escrow Services duties under this Agreement by depositing all escrowed funds with a court of competent jurisdiction. If an alternate Escrow Agent is so designated, Escrow Services shall be discharged from Escrow Services duties under this Agreement, the General Escrow Instructions and the Transaction Escrow Instructions by delivering all escrowed funds to such person or entity. Upon payment of the escrow funds pursuant to this Agreement, Escrow Services shall be fully released from any and all liability and obligations with respect to the escrow funds and the Transaction.

11. Canceling a Transaction. If a Transaction cannot be completed for any reason, including cancellation by Escrow Services for any reason, Escrow Services will notify each User in such Transaction by e-mail, to the e-mail address each has provided to Escrow Services. In Escrow Services's sole discretion, Escrow Services may cancel any Transaction if each User to a Transaction fails to agree on the terms as required in the Transaction Details Screens by clicking the "Agree" button as requested on the Site. You may cancel a Transaction as provided in this Agreement, on the General Escrow Instructions or in the Transaction Escrow Instructions.

12. Questions about the Services. You may inquire about payments made through the Service by calling the toll-free number that appears on the Site or by filling out the customer service form. If you believe an error has been made or there has been any unauthorized use of your Account or the Services, you agree to call or send an e-mail as soon as possible, but no later than forty-eight hours after you became aware of an error. When you contact Escrow Services, please be prepared to provide your name, Escrow Services reference number and your email address you have registered on the Escrow Services site.

13. Statements, Verification. You agree that all disclosures and communications regarding this Agreement and the Service shall be made by e-mail or on the Site, unless the parties make other arrangements as set forth in the General Escrow Instructions.

14. Digital Identification. You understand and agree that Escrow Services will create, issue, and verify a digital identification (a "Digital ID") for each User. This Digital ID is attached to each accepted electronic document and notification e-mails. You agree that your Digital ID is a valid "Electronic Signature." Please review the General Escrow Instructions for more information about Escrow Services's use of the Digital ID.

15. Fees. Unless otherwise agreed upon by each User in the Transaction, Buyer agrees to pay the fees for the Services that are disclosed on the Site at the time the completed Transaction Escrow Instructions are agreed to by all such Users, as well as any other fees, including, without limitation, third party service fees (e.g., shipping, appraisal, inspection, etc.). Once paid, Escrow Services fees are nonrefundable. Escrow Services fees may change from time to time in Escrow Services's absolute and sole discretion. Escrow Services is not responsible for payment of any sales, use, personal property or other governmental tax or levy imposed on any items purchased or sold through the Services or otherwise arising from the Transaction.

16. Security. Escrow Services uses secure sockets layer ("SSL"), a security protocol that provides data encryption, server authentication, and message integrity for connections to the Internet to ensure that the data you provide Escrow Services is not transmitted over the Internet unencrypted and cannot be viewed by unauthorized individuals. Escrow Services has also implemented a security system requiring a user ID and a password to access your transactions on the Site. You agree not to give your password to any other person or entity and to protect it from being used or discovered by anyone else.

17. Disclaimers. You expressly agree that your use of the Services is at your sole risk. The Services are provided on a strictly "as is" and "as available" basis. Escrow Services MAKES NO WARRANTY WITH REGARD TO THE UNDERLYING TRANSACTION, ANY ITEMS OBTAINED BY YOU THROUGH THE USE OF THE SITE OR THE SERVICES, THAT THE SERVICES WILL MEET YOUR REQUIREMENTS, OR THAT THE SERVICES OR THE SITE WILL BE UNINTERRUPTED, TIMELY, OR ERROR FREE.

Escrow Services expressly disclaims any and all express and implied warranties, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose and non-infringement. Escrow Services shall not be liable or responsible for those guarantees, warranties and representations, if any, offered by any Seller of items. No advice or information, whether oral or written, obtained by you from Escrow Services or through the Services shall create any warranty not expressly made herein.

You acknowledge and agree that Escrow Services does not endorse the website of any third party, or assume responsibility or liability for the accuracy of any material contained therein, or any infringement of third party intellectual property rights arising therefrom, or any fraud or other crime facilitated thereby. In no event will Escrow Services be liable for any act or omission of any third party, including, but not limited to, your financial institution, any payment system, any third party service provider, any provider of telecommunications services, Internet access or computer equipment or software, any mail or delivery service or any payment or clearing house system or for any circumstances beyond Escrow Services's control (including but not limited to, fire, flood or other natural disaster, war, riot, strike, terrorism, act of civil or military authority, equipment failure, computer virus, infiltration or hacking by a third party, or failure or interruption of electrical, telecommunications or other utility services).

18. Limitation of Liability. TO THE EXTENT PERMITTED BY APPLICABLE LAW, NEITHER Escrow Services NOR ITS AFFILIATES, SHALL BE LIABLE FOR ANY DAMAGES, WHETHER DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL, RELATING TO YOUR USE OF THE SITE OR THE SERVICES OR YOUR INABILITY TO USE THE SITE OR THE SERVICES.

19. Termination of Services. Escrow Services may suspend or terminate your use of the Services at any time, without notice for any reason, in Escrow Services's sole discretion. Except as warranted by risk to the security, privacy or integrity of the Services, Escrow Services will attempt to provide you with prior notice of the suspension or termination of the Services by sending you an e-mail, but Escrow Services is not obligated to do so. You shall remain liable for all Transactions you initiate through the Services prior to such termination, and the performance of your obligations, including but not limited to, the delivery of the items and the payment of all amounts you owe prior to termination or discontinuation of your use of the Services. You agree to pay all costs and expenses (including reasonable attorneys' fees) that Escrow Services may incur in order to (a) collect any amounts you owe under this Agreement, the General Escrow Instructions, or the Transaction Escrow Instructions or (b) to initiate an arbitration or judicial proceeding to resolve a dispute between Buyer and Seller, as set forth in the General Escrow Instructions.

20. Non-Transferability of the Services. You may not assign this Agreement or the Escrow Instructions to any other person or entity. Your right to use the Services shall not be sold or transferred to any other person or entity without the prior written consent of Escrow Services. Escrow Services may assign this Agreement upon notice to you. Any assignment or transfer in violation of this provision shall be null and void.

21. Modifications. Escrow Services reserves the right to change this Agreement, or any portion of it, at any time, without prior notice, provided that no such change will apply to a Transaction once the Users to such Transaction have agreed to the Transaction Escrow Instructions. You understand that the most recent version of this Agreement will be located on the Site.

22. Notices. Notices from Escrow Services to you will be given by e-mail, or by general posting on the Site. You may contact Escrow Services by filling out the customer support form or such other email address as Escrow Services posts as its address for notice on the Site in the most recent version of the Terms of Use

23. Indemnification. You agree to indemnify and hold Escrow Services, Escrow Services affiliates and their respective officers, directors, shareholders, employees and assigns, harmless from any claim, demand, expense or damage, including reasonable attorneys' fees and court costs, arising from or relating to your use of the Services or any violation of this Agreement, the rules contained on the Site or the Transaction Escrow Instructions, including, without limitation, payment of Escrow Services fees and any charge backs from a card organization or reversal or nonpayment of any credit or debit entry.

24. Miscellaneous. In the event of any dispute, claim, question, or disagreement arising from or relating to, this Agreement or to the Underlying Transaction, or breach of any of them, you agree to resolve such dispute in the manner set forth in the General Escrow Instructions.

This Agreement shall be governed by the laws of the State of California. Any dispute shall be resolved pursuant to the Dispute Resolution and Governing Law/Venue provisions of the General Escrow Instructions. This Agreement in conjunction with the General Escrow Instructions and rules contained on the Site constitutes the entire agreement between Escrow Services and you relating to the subject matter hereof and supersedes all prior or contemporaneous understandings, agreements, communications and/or advertising with respect to such subject matter. If there is a conflict between the terms and conditions of this Agreement, the rules contained on the Site, and/or the General Escrow Instructions, then the conflicting terms set forth in the General Escrow Instructions shall control first, these Terms of Use shall control second and the rules contained on the Site shall control third. The General Escrow Instructions are incorporated herein by this reference.

Escrow Services's failure to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision unless acknowledged and agreed to by Escrow Services in writing.

If any term or other provision of this Agreement is invalid, illegal or incapable of being enforced by any law or public policy, all other terms and provisions of this Agreement shall nevertheless remain in full force and effect for so long as the economic or legal substance of the transactions contemplated hereby is not affected in any manner materially adverse to any party hereto.

Escrow Services may assign this Agreement to any current or future affiliated company and to any successor in interest. Escrow Services also may delegate certain of Escrow Services rights and responsibilities under the Agreement to independent contractors or other third parties.

If you are a registered User of the Site, then each time you request the Services will constitute your agreement to these Terms of Use, as amended from time to time in Escrow Services's sole discretion, and evidence that you have read, understood and accepted the then applicable Terms of Use.